---CAN LAM
--1.TAO ROLE

--2.CAP QUYEN CHO ROLE --> [RBAC]
---3.VIET PROC: TAO TAI KHOAN --> CAP ROLE CHO TAI KHOAN --> [DAC]


--TAO ROLE
--1.NHANVIEN
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE NHANVIEN;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 
/

--2.NVQL
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE NVQL;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

/
--3.TRUONG PHONG
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE TRUONGPHONG;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

/
--4.TAI CHINH
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE TAICHINH;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 


/
--5.NHAN SU
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE NHANSU;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

/
--6.TRUONG DE AN
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE TRUONGDEAN;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

/
--7.GIAMDOC
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE GIAMDOC;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 


--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--DROP ROLE GIAMDOC;
--ALTER SESSION SET "_ORACLE_SCRIPT"=False; 


ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
create User NV0001 IDENTIFIED BY NV0001;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 
                                        
GRANT CONNECT TO NV0001;
GRANT GIAMDOC TO NV0001;

----------------------NHANVIEN-----------------
--NHANVIEN 0091
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER NV0091 IDENTIFIED BY NV0091;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

--CAP QUYEN
GRANT CONNECT TO NV0091;
GRANT NHANVIEN TO NV0091;


-------------------------NVQL-----------
--NHANVIEN 5001-
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER NV5001 IDENTIFIED BY NV5001;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

--CAP QUYEN
GRANT CONNECT TO NV5001;
GRANT NVQL TO NV5001;


-------------------------NHANSU-----------
--NHANVIEN NV3005-
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER NV3005 IDENTIFIED BY NV3005;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

--CAP QUYEN
GRANT CONNECT TO NV3005;
GRANT NHANSU TO NV3005;


-------------------------TRUONGPHONG-----------
--NHANVIEN NV1001-
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER NV1001 IDENTIFIED BY NV1001;
ALTER SESSION SET "_ORACLE_SCRIPT"=False; 

--CAP QUYEN
GRANT CONNECT TO NV1001;
GRANT TRUONGPHONG TO NV1001;




SELECT * FROM USER_ROLE_PRIVS WHERE GRANTED_ROLE='GIAMDOC'; 
SELECT * FROM DBA_TAB_PRIVS WHERE OWNER='GROUP08';

select * from all_views where owner='GROUP08';

GRANT SELECT ON GROUP08.XemThongTinCaNhan TO GIAMDOC
GRANT SELECT ON GROUP08.XemThongTinPhanCong TO GIAMDOC



----------------------------POLICY----------------------------------------------
---------------------------------CS1-------------------------------------------
---NHAN VIEN
--Nhan vien:
--CS1:
--CS1-1. Xem moi thuoc tinh tren quan he NHANVIEN
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW XemThongTinCaNhan
AS
SELECT * FROM GROUP08.qlnv_nhanvien
WHERE MANV=SYS_CONTEXT('USERENV','SESSION_USER'); 
/

CONNECT GROUP08/GROUP08;
--CS1-2. Xem moi thuoc tinh cua minh tren quan he PHANCONG
CREATE VIEW XemThongTinPhanCong 
AS
SELECT * FROM GROUP08.qlnv_phancong 
WHERE MANV=SYS_CONTEXT('USERENV','SESSION_USER'); 


--CS1-3. Chinh sua NGAYSINH, DIACHI, SODT lien quan den chinh Nhan Vien
--CREATE TRIGGER (Ap len view XemThongTinCaNhan)
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER CapNhat_TTCaNhan
INSTEAD OF UPDATE
ON XemThongTinCaNhan
FOR EACH ROW
DECLARE
BEGIN
UPDATE GROUP08.qlnv_nhanvien 
SET NGAYSINH = :NEW.NGAYSINH, DIACHI = :NEW.DIACHI, SODT = :NEW.SODT
 WHERE username = :NEW.username;
END;


--CS1-4: Xem toan bo du lieu cua quan he PHONGBAN, DEAN
GRANT SELECT ON GROUP08.qlnv_phongban to NHANVIEN; --ROLE: NHANVIEN
GRANT SELECT ON GROUP08.qlnv_dean to NHANVIEN;

--GRANT CAC VIEW NAY CHO NHANVIEN

---------------------------------CS2-------------------------------------------
--CS2: QLNV
--CS2-1. Xem cac nhan vien khac do minh quan ly (tru LUONG,PHU CAP)
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW NVQL_XemThongTin_NV
AS
SELECT MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG FROM GROUP08.qlnv_nhanvien
WHERE MANQL=SYS_CONTEXT('USERENV','SESSION_USER'); 

--CS2-2: Xem Phan cong cua nhan vien minh quan ly
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW NVQL_Xem_PC
AS
SELECT PC.* FROM GROUP08.qlnv_phancong PC 
JOIN GROUP08.qlnv_NHANVIEN NV ON
PC.MANV=NV.MANV 
WHERE SYS_CONTEXT('USERENV','SESSION_USER')= NV.MANQL 
OR PC.MANV=SYS_CONTEXT('USERENV','SESSION_USER');
/

---------------------------------CS3-------------------------------------------
--CS3-1: Xem thong tin Nhan vien thuoc phong ban minh quan ly
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW TP_XemThongTin_NV
AS
SELECT MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG 
FROM GROUP08.qlnv_nhanvien
WHERE PHG=(SELECT MAPB FROM GROUP08.qlnv_phongban WHERE 
TRPHG=SYS_CONTEXT('USERENV','SESSION_USER')); 

--VIEW: Chi thao tac duoc voi nhung THUOC TINH DUOC SELECT TRONG VIEW
--CS3-2: Them, xoa, cap nhat tren quan he PHANCONG lien quan den cac nhan vien thuoc 
--phong ban minh lam truong 
--Xem view TP XemPC
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW TP_XemPC_NV
AS 
SELECT PC.MANV, PC.MADA, PC.THOIGIAN FROM GROUP08.qlnv_phancong PC 
JOIN GROUP08.qlnv_NHANVIEN NV ON PC.MANV=NV.MANV 
WHERE PC.MANV IN (SELECT MANV FROM GROUP08.QLNV_NHANVIEN WHERE 
PHG=(SELECT MAPB FROM GROUP08.QLNV_PHONGBAN WHERE TRPHG=SYS_CONTEXT('USERENV','SESSION_USER')))
WITH CHECK OPTION;



--TRIGGER - Truong phong them phan cong----------------------------------------------------------------------------
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER TP_ThemPC_NV
INSTEAD OF INSERT ON TP_XemPC_NV
FOR EACH ROW
DECLARE PHONGNV VARCHAR2(20);
PHONGTRPHG VARCHAR2(20);
BEGIN
DBMS_OUTPUT.put_line(:new.MANV); 
DBMS_OUTPUT.put_line(:new.MADA); 
DBMS_OUTPUT.put_line(:NEW.THOIGIAN);
--THEM DIEU KIEN THOA MOI CHO INSERT
    SELECT PHG INTO PHONGNV FROM GROUP08.QLNV_NHANVIEN WHERE 
    MANV=:NEW.MANV;

    SELECT MAPB INTO PHONGTRPHG FROM GROUP08.QLNV_PHONGBAN 
    WHERE TRPHG=SYS_CONTEXT('USERENV','SESSION_USER');
    
IF PHONGNV=PHONGTRPHG THEN
    INSERT INTO GROUP08.qlnv_phancong(MANV,MADA,THOIGIAN)   
    VALUES (:new.MANV,:new.MADA,:new.THOIGIAN);
END IF;
END;
---------------------------------XOA-------------------------------
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER TP_Xoa_NV
INSTEAD OF DELETE
ON TP_XemPC_NV
FOR EACH ROW
BEGIN
    DELETE FROM GROUP08.qlnv_phancong where manv=:old.manv;
END;

------------------------------CAP NHAT--------------------------------------
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER TP_CapNhat_NV
INSTEAD OF UPDATE
ON TP_XemPC_NV
FOR EACH ROW
BEGIN
    UPDATE GROUP08.qlnv_phancong 
    SET MANV=:NEW.MANV, MADA=:NEW.MADA, THOIGIAN=:NEW.THOIGIAN
    where manv=:new.manv;
END;

---------------------------------CS4-------------------------------------------
--CS4: TAI CHINH
--CS4-1: Nhu nhan vien

--CS4: Xem toan bo quan he NHANVIEN va PHANCONG, Sua tren thuoc tinh (LUONG,PHUCAP)
GRANT SELECT ON GROUP08.qlnv_NHANVIEN TO TAICHINH
GRANT SELECT ON GROUP08.qlnv_PHANCONG TO TAICHINH
GRANT UPDATE (LUONG,PHUCAP) ON GROUP08.qlnv_NHANVIEN TO TAICHINH


---------------------------------CS5-------------------------------------------
--CS5: NHAN SU
--CS5-1: Nhu nhan vien

--CS5-2: Them, cap nhat tren quan he PHONGBAN
GRANT INSERT,UPDATE  ON GROUP08.qlnv_PHONGBAN TO NHANSU

--CS5-3: Them, cap nhat du lieu trong quan he NHANVIEN voi cac gia tri truong LUONG,
--PHUCAP la mang gia tri mac dinh la NULL (khong duoc xem LUONG,PHUCAP cua nguoi khac
--va khong duoc cap nhat LUONG,PHUCAP
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE VIEW NS_XemThongTin_NV
AS
SELECT MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,
DECODE (MANV, USER, LUONG, NULL) LUONG,
DECODE (MANV, USER, PHUCAP, NULL) PHUCAP,
VAITRO,MANQL,PHG
FROM GROUP08.qlnv_nhanvien;
/

--------Them Nhan vien----------------(KHONG CHO THEM LUONG,PHUCAP)
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER NS_Them_NV
INSTEAD OF INSERT
ON NS_XemThongTin_NV
FOR EACH ROW
BEGIN 
    INSERT INTO GROUP08.QLNV_NHANVIEN(MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,LUONG,PHUCAP,VAITRO,MANQL,PHG)
    VALUES(:NEW.MANV,:NEW.TENNV,:NEW.PHAI,:NEW.NGAYSINH,:NEW.DIACHI,:NEW.SODT,NULL,NULL,:NEW.VAITRO,:NEW.MANQL,:NEW.PHG);
END;

/
--Trigger de cap nhat (Khong cap nhat LUONG,PHUCAP) --TAM THOI KHONG CHO SUA VAI TRO
CONNECT GROUP08/GROUP08;
CREATE OR REPLACE TRIGGER NS_CapNhatThongTin_NV
INSTEAD OF UPDATE
ON NS_XemThongTin_NV
FOR EACH ROW
BEGIN
IF (:OLD.LUONG IS NULL) AND (:OLD.PHUCAP IS NULL) THEN 
    DBMS_OUTPUT.put_line(:NEW.manv); 
    UPDATE GROUP08.qlnv_NHANVIEN
    SET TENNV=:NEW.TENNV, PHAI=:NEW.PHAI, NGAYSINH=:NEW.NGAYSINH,
    SODT=:NEW.SODT,MANQL=:NEW.MANQL, PHG=:NEW.PHG
    where manv=:new.manv;
end if;
END;

/
---CS6:
--CS6-1: Nhu nhan vien

--CS6: Them, cap nhat DEAN
GRANT INSERT,UPDATE,DELETE  ON GROUP08.qlnv_DEAN TO GIAMDOC
